#pragma once

namespace Jupiter::Io {

	enum class AssetPropertyGroups {
		UNDEFINED = 0,

		TEXTURE_PROPERTIES = 1,
		MODEL_PROPERTIES = 2
	};

	enum class AssetPropertyIdentifiers {
		UNDEFINED = 0,

		// ----- Texture ----- 
		TEXTURE_MIN_FILTER = 1,
		TEXTURE_MAG_FILTER = 2,
		TEXTURE_WRAP_S = 3,
		TEXTURE_WRAP_T = 4,
		TEXTURE_WRAP_R = 5,
	};

	enum class AssetPropertyValues {
		UNDEFINED = 0,

		// ----- Texture -----
		TEXTURE_NEAREST = 1,
		TEXTURE_LINEAR = 2,
		TEXTURE_NEAREST_MIPMAP_NEAREST = 3,
		TEXTURE_LINEAR_MIPMAP_NEAREST = 4,
		TEXTURE_NEAREST_MIPMAP_LINEAR = 5,
		TEXTURE_LINEAR_MIPMAP_LINEAR = 6,
		TEXTURE_REPEAT = 7,
		TEXTURE_CLAMP_TO_EDGE = 8,
		TEXTURE_CLAMP_TO_BORDER = 9,
		TEXTURE_MIRRORED_REPEAT = 10,
		TEXTURE_MIRRORED_CLAMP_TO_EDGE = 11
	};
}